// VARIABLES FOR PROJECT REDUCER
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const SET_TITLE = "SET_TITLE";
export const SET_CONTENT = "SET_CONTENT";
export const SET_TAGS = "SET_TAGS";
export const SET_CREATEDAT = "SET_CREATEDAT";

// VARIABLES FOR AUTH REDUCER
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SWITCH_LOADING_STATUS = "SWITCH_LOADING_STATUS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_USERID = "SET_USERID";
export const SET_POSTID = "SET_POSTID";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_PROFILE_IMAGE_URL = "SET_PROFILE_IMAGE_URL";
export const SET_USER_NAME = "SET_USER_NAME";

// VARIABLES FOR PROFILE REDUCER
export const SWITCH_TOGGLE = "SWITCH_TOGGLE";

// VARIABLES FOR EDITOR REDUCER
export const UPDATE_EDITOR = "UPDATE_EDITOR";

// VARIABLES FOR TAG REDUCER
export const DISPLAY_ON = "DISPLAY_ON";
export const DISPLAY_OFF = "DISPLAY_OFF";
export const ADD_TAG = "ADD_TAG";
export const DELETE_TAG = "DELETE_TAG";

// VARIABLES FOR COMMENT REDUCER
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_ROOTCOMMENTS = "SET_ROOTCOMMENTS";
export const SET_REPLIES = "SET_REPLIES";
