// VARIABLES FOR PROJECT REDUCER
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";

// VARIABLES FOR AUTH REDUCER
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
